import { ChartDataPoint, Stats, User } from "@/types";

export const mockStats: Stats = {
  totalRevenue: 48320,
  totalUsers: 3842,
  activeUsers: 2710,
  conversionRate: 4.6,
  revenueChange: 12.5,
  usersChange: 8.2,
  activeUsersChange: -3.1,
  conversionChange: 1.2,
};

export const mockChartData: ChartDataPoint[] = [
  { month: "Jan", revenue: 28000, users: 2100 },
  { month: "Feb", revenue: 32000, users: 2400 },
  { month: "Mar", revenue: 27000, users: 2200 },
  { month: "Apr", revenue: 38000, users: 2800 },
  { month: "May", revenue: 43000, users: 3100 },
  { month: "Jun", revenue: 41000, users: 3000 },
  { month: "Jul", revenue: 48000, users: 3400 },
  { month: "Aug", revenue: 52000, users: 3600 },
  { month: "Sep", revenue: 47000, users: 3300 },
  { month: "Oct", revenue: 55000, users: 3800 },
  { month: "Nov", revenue: 59000, users: 4100 },
  { month: "Dec", revenue: 48320, users: 3842 },
];

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Alice Johnson",
    email: "alice@example.com",
    role: "admin",
    status: "active",
    joinedAt: "2024-01-12",
    avatar: "AJ",
  },
  {
    id: "2",
    name: "Bob Smith",
    email: "bob@example.com",
    role: "user",
    status: "active",
    joinedAt: "2024-02-08",
    avatar: "BS",
  },
  {
    id: "3",
    name: "Carol White",
    email: "carol@example.com",
    role: "viewer",
    status: "inactive",
    joinedAt: "2024-03-15",
    avatar: "CW",
  },
  {
    id: "4",
    name: "David Brown",
    email: "david@example.com",
    role: "user",
    status: "active",
    joinedAt: "2024-03-22",
    avatar: "DB",
  },
  {
    id: "5",
    name: "Eva Martinez",
    email: "eva@example.com",
    role: "admin",
    status: "active",
    joinedAt: "2024-04-01",
    avatar: "EM",
  },
  {
    id: "6",
    name: "Frank Lee",
    email: "frank@example.com",
    role: "user",
    status: "inactive",
    joinedAt: "2024-04-18",
    avatar: "FL",
  },
  {
    id: "7",
    name: "Grace Kim",
    email: "grace@example.com",
    role: "viewer",
    status: "active",
    joinedAt: "2024-05-05",
    avatar: "GK",
  },
  {
    id: "8",
    name: "Henry Chen",
    email: "henry@example.com",
    role: "user",
    status: "active",
    joinedAt: "2024-05-20",
    avatar: "HC",
  },
  {
    id: "9",
    name: "Iris Patel",
    email: "iris@example.com",
    role: "user",
    status: "active",
    joinedAt: "2024-06-03",
    avatar: "IP",
  },
  {
    id: "10",
    name: "Jake Wilson",
    email: "jake@example.com",
    role: "viewer",
    status: "inactive",
    joinedAt: "2024-06-14",
    avatar: "JW",
  },
  {
    id: "11",
    name: "Demo User",
    email: "demo@dashify.dev",
    role: "user",
    status: "active",
    joinedAt: "2024-01-01",
    avatar: "DU",
  },
];
